### ISSUE TITLE
您好请问您的实现有相关论文吗？

### ISSUE THREAD

**Issue by npq567** [taishan1994/pytorch_bert_event_extraction#1]
您好请问您的实现有相关论文吗？

**Comment by taishan1994** [comment]
> 您好请问您的实现有相关论文吗？

没有额，主要是参考阅读理解和QA的思想整的，应该有这方面的论文，你可以去查一下。

**Comment by npq567** [comment]
谢谢您的回答，我还有一个问题就是您的hfl_chinese-roberta-wwm-ext是pytorch版本的吗

**Comment by taishan1994** [comment]
> 谢谢您的回答，我还有一个问题就是您的hfl_chinese-roberta-wwm-ext是pytorch版本的吗

是的，在hugging face上，readme.md里面有链接。

**Comment by npq567** [comment]
请问我运行测试的时候出现了这个错误Traceback (most recent call last):
  File "main.py", line 293, in <module>
    bertForMrc.test(model, model_path)
  File "main.py", line 150, in test
    model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path)
  File "/home/npq20/pytorch_bert_event_extraction-main/utils/trainUtils.py", line 89, in load_model_and_parallel
    model.load_state_dict(torch.load(ckpt_path, map_location=torch.device('cpu')), strict=strict)
  File "/home/npq20/miniconda3/envs/gpt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BertMrcModel:
	Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids".
是因为什么问题呢我把这行注释了 结果准确率就都为0了

**Comment by taishan1994** [comment]
> 请问我运行测试的时候出现了这个错误Traceback (most recent call last):
> File "main.py", line 293, in
> bertForMrc.test(model, model_path)
> File "main.py", line 150, in test
> model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path)
> File "/home/npq20/pytorch_bert_event_extraction-main/utils/trainUtils.py", line 89, in load_model_and_parallel
> model.load_state_dict(torch.load(ckpt_path, map_location=torch.device('cpu')), strict=strict)
> File "/home/npq20/miniconda3/envs/gpt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for BertMrcModel:
> Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids".
> 是因为什么问题呢我把这行注释了 结果准确率就都为0了

检查模型是否是正确的，路径是否是正确的。

**Comment by xiacoder** [comment]
> 请问我运行测试的时候出现了这个错误Traceback (most recent call last): File "main.py", line 293, in bertForMrc.test(model, model_path) File "main.py", line 150, in test model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path) File "/home/npq20/pytorch_bert_event_extraction-main/utils/trainUtils.py", line 89, in load_model_and_parallel model.load_state_dict(torch.load(ckpt_path, map_location=torch.device('cpu')), strict=strict) File "/home/npq20/miniconda3/envs/gpt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for BertMrcModel: Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids". 是因为什么问题呢我把这行注释了 结果准确率就都为0了

请问您最后这个问题是如何解决的呢？我也遇到了相同的问题

**Comment by npq567** [comment]
> > 请问我运行测试的时候出现了这个错误Traceback (most recent call last): File "main.py", line 293, in bertForMrc.test(model, model_path) File "main.py", line 150, in test model, device = trainUtils.load_model_and_parallel(model, self.args.gpu_ids, model_path) File "/home/npq20/pytorch_bert_event_extraction-main/utils/trainUtils.py", line 89, in load_model_and_parallel model.load_state_dict(torch.load(ckpt_path, map_location=torch.device('cpu')), strict=strict) File "/home/npq20/miniconda3/envs/gpt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for BertMrcModel: Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids". 是因为什么问题呢我把这行注释了 结果准确率就都为0了
> 
> 请问您最后这个问题是如何解决的呢？我也遇到了相同的问题
我记得是路径问题
