### ISSUE TITLE
请问代码怎么打不开？main.sh  main.py

### ISSUE THREAD

**Issue by RyanTong2020** [taishan1994/pytorch_bert_event_extraction#2]

**Comment by taishan1994** [comment]
> 打开后是这样的： version https://git-lfs.github.com/spec/v1 oid sha256:8b6739eb05671a4367419f1b3ca418ea1230397cf66831cb2f353d1acbbcdbf1 size 1312

可能当时上传使用了大文件的传输方式，你把这个仓库下载下来再看应该就可以了

**Comment by RyanTong2020** [comment]
好的，我看需要用到lfs，谢谢
