### ISSUE TITLE
main运行时出错

### ISSUE THREAD

**Issue by xiacoder** [taishan1994/pytorch_bert_event_extraction#3]
RuntimeError: Error(s) in loading state_dict for BertMrcModel:
	Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids"

您好，请问这个错误应该如何解决？

**Comment by taishan1994** [comment]
> RuntimeError: Error(s) in loading state_dict for BertMrcModel: Unexpected key(s) in state_dict: "bert_module.embeddings.position_ids"
> 
> 您好，请问这个错误应该如何解决？

加载的模型错误吧
