### ISSUE TITLE
大佬求教

### ISSUE THREAD

**Issue by ghost** [taishan1994/pytorch_bert_event_extraction#7]
用django框架搭建服务时报错AttributeError: Can't get attribute 'MRCBertFeature' on <module '__main__' from 'manage.py'>

也显示引入了from event_extract.tasks.preprocess import MRCBertFeature

**Comment by taishan1994** [comment]
> 用django框架搭建服务时报错AttributeError: Can't get attribute 'MRCBertFeature' on <module '**main**' from 'manage.py'>
> 
> 也显示引入了from event_extract.tasks.preprocess import MRCBertFeature

django不太了解，建议使用flask或者fastapi
